/**
 * TODO Copyright Notice
 */
package com.oracle.activation.cisco.isp.x1_0.fiber_cpe.add;

import com.oracle.activation.cisco.isp.x1_0.fiber_cpe.add.generated.*;
import com.orcl.activation.cisco.isp.x1_0.IspConnectionHandler;
import com.orcl.activation.cisco.isp.x1_0.helper.ISPConstants;
import com.orcl.activation.cisco.isp.x1_0.helper.ISPHelper;
import com.orcl.activation.cisco.isp.x1_0.request.ProvisionRequest;
import com.orcl.activation.cisco.isp.x1_0.request.QueryRequest.Credential;
import com.orcl.activation.cisco.isp.x1_0.response.ProvisionResponse;
import com.orcl.activation.cisco.isp.x1_0.response.QueryResponse.Service;

import java.io.StringReader;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Unmarshaller;

import com.mslv.activation.jinterpreter.JProcessor;
import com.mslv.studio.activation.implementation.IConnectionHandler;
import com.mslv.studio.activation.implementation.ILogger;
import com.mslv.studio.activation.implementation.IExitType;

public class AddFiber_cpeProcessor implements AddFiber_cpeProcessorInterface {

	/*
	 * The logger to use for all log information generated by this processor.
	 */
	private ILogger logger = null;
	private String responseCode = null;
	private String responseDesc = null;
	private JProcessor jproc=null;

	public void execute(AddFiber_cpeInput parms, AddFiber_cpeOutput output, IConnectionHandler connection,
			IExitType exitType, ISystemParameters systemParameters) throws Exception {

		ISPHelper ispHelper = new ISPHelper(); 
		try {

			logger.logDebug("RetrieveMacProcessor: execute() - Completed step A of execution.");
			logger.logDebug("JPROC CSDL_CMD "+jproc.getParam(ISPConstants.CSDL_CMD));

			IspConnectionHandler connHdlr = (IspConnectionHandler) connection;

			// Read input parameters
			String mcli = parms.getMCLI();
			String downloadspeed = parms.getDownloadSpeed();
			String ipaddress = parms.getIPAddress();
			String password = parms.getPassword();
			String serialnumber = parms.getSerialNumber();
			String uploadspeed = parms.getUploadSpeed();
			String vendor = parms.getVendor();
			String macAddress = parms.getMACAddress();
			String model = parms.getModel();
			String username = parms.getUsername();
			String cpetype = parms.getCPEType();

			// Check if parameter is not null or have no value
			ispHelper.isNotNull(macAddress, ISPConstants.MACAddress);
			ispHelper.isNotNull(serialnumber, ISPConstants.SERIALNUMBER);

			// Construct Provision Request
			ProvisionRequest provReq = new ProvisionRequest();
			provReq.setAction(ISPConstants.ACTION_ADD);
			provReq.setMACAddress(macAddress);
			provReq.setSerialNumber(serialnumber);
			
			Service service=new Service();
			service.setCPEType(cpetype);
			service.setDownloadSpeed(downloadspeed);
			service.setIPAddress(ipaddress);
			service.setModel(model);
			service.setUploadSpeed(uploadspeed);
			service.setVendor(vendor);
			
			Credential cred = new Credential();
			cred.setUsername(connHdlr.getUserId());
			cred.setPassword(connHdlr.getPassword());

			provReq.getService();
			provReq.getCredential();
			
			String provReqStr = ispHelper.getRequestString(provReq);
			logger.logDebug("Provision Request - " + provReqStr);

			
			//Not connected with Network so no need of checking loopback condition
			//if (!systemParameters.isLoopback()) {

			String provResStr = connHdlr.sendRequest(provReqStr);
			
			Unmarshaller unmarshaller = JAXBContext.newInstance(ProvisionResponse.class).createUnmarshaller();
			// unmarshaller.setProperty(Unmarshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);

			ProvisionResponse provRes = (ProvisionResponse) unmarshaller.unmarshal(new StringReader(provResStr));

			int Result = provRes.getResult();

			responseCode = Integer.toString(Result);
			responseDesc = provRes.getDesc();
		}
		catch(Exception ex)
		{
			responseCode = ispHelper.getExceptionResponseCode(ex);
			responseDesc = ex.getMessage()+" in "+jproc.getParam(ISPConstants.CSDL_CMD);
			logger.logError("Exception occurred: "+ex.toString());
		}

		finally
		{
			String exitValue = exitType.setTypeByMatch(responseCode, 
					responseDesc, IExitType.FAIL);

			if ((exitValue != null) && (exitValue.equals(IExitType.FAIL))) {
				output.addActionParameter(PARAMETER_ERROR, responseDesc);
				output.addActionParameter(PARAMETER_VENDOR, VENDOR);
				output.addActionParameter(PARAMETER_TECHNOLOGY, TECHNOLOGY);
				output.addActionParameter(PARAMETER_SOFTWARE_LOAD, SOFTWARE_LOAD);
			}
		}
	}

	/**
	 * The init method is called prior to the execute method.  Additional initialization logic may be added as necessary.
	 *
	 * @param processor a reference to the underlying proxy processor.  Use of this parameter is strongly discouraged.
	 * @param logger a logging instance to be used for all processor logging.
	 */
	public void init(Object processor, ILogger logger) {
		this.logger = logger;
		//If connected to network set Loopback response
		//responseCode = ISPConstants.DEFAULT_SUCCESS_CODE;
		//responseDesc = ISPConstants.SUCCESS;

		if (processor instanceof JProcessor) {
			jproc = (JProcessor) processor;
		}	
	}

}