//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.20 at 07:40:22 PM IST 
//


package com.orcl.activation.cisco.isp.x1_0.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.orcl.activation.cisco.isp.x1_0.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.orcl.activation.cisco.isp.x1_0.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryResponse }
     * 
     */
    public QueryResponse createQueryResponse() {
        return new QueryResponse();
    }

    /**
     * Create an instance of {@link TerminateResponse }
     * 
     */
    public TerminateResponse createTerminateResponse() {
        return new TerminateResponse();
    }

    /**
     * Create an instance of {@link ProvisionResponse }
     * 
     */
    public ProvisionResponse createProvisionResponse() {
        return new ProvisionResponse();
    }

    /**
     * Create an instance of {@link QueryResponse.Service }
     * 
     */
    public QueryResponse.Service createQueryResponseService() {
        return new QueryResponse.Service();
    }

    /**
     * Create an instance of {@link ModifyResponse }
     * 
     */
    public ModifyResponse createModifyResponse() {
        return new ModifyResponse();
    }

}
