/**
 * TODO Copyright Notice
 */
package com.orcl.activation.cisco.isp.x1_0.fiber_cpe.change;

import com.orcl.activation.cisco.isp.x1_0.IspConnectionHandler;
import com.orcl.activation.cisco.isp.x1_0.fiber_cpe.change.generated.*;
import com.orcl.activation.cisco.isp.x1_0.helper.ISPConstants;
import com.orcl.activation.cisco.isp.x1_0.helper.ISPHelper;
import com.orcl.activation.cisco.isp.x1_0.request.ModifyRequest;
import com.orcl.activation.cisco.isp.x1_0.request.ModifyRequest.Credential;
import com.orcl.activation.cisco.isp.x1_0.request.ModifyRequest.Service;
import com.orcl.activation.cisco.isp.x1_0.response.ModifyResponse;
import com.orcl.activation.cisco.isp.x1_0.response.ProvisionResponse;
import com.orcl.activation.cisco.isp.x1_0.response.QueryResponse;

import java.io.StringReader;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Unmarshaller;

import com.mslv.activation.jinterpreter.JProcessor;
import com.mslv.studio.activation.implementation.IConnectionHandler;
import com.mslv.studio.activation.implementation.ILogger;
import com.mslv.studio.activation.implementation.IExitType;

public class ChangeFiber_cpeProcessor implements ChangeFiber_cpeProcessorInterface {

	/*
	 * The logger to use for all log information generated by this processor.
	 */
	private ILogger logger = null;
	private String responseCode = null;
	private String responseDesc = null;
	private JProcessor jproc=null;

	public void execute(ChangeFiber_cpeInput parms, ChangeFiber_cpeOutput output, IConnectionHandler connection,
			IExitType exitType, ISystemParameters systemParameters) throws Exception {

		ISPHelper ispHelper = new ISPHelper(); 
		try {

			logger.logDebug("RetrieveMacProcessor: execute() - Completed step A of execution.");
			logger.logDebug("JPROC CSDL_CMD "+jproc.getParam(ISPConstants.CSDL_CMD));

			IspConnectionHandler connHdlr = (IspConnectionHandler) connection;

			// Read input parameters
			String mcli = parms.getMCLI();
			String downloadspeed = parms.getDownloadSpeed();
			String serialnumber = parms.getSerialNumber();
			String uploadspeed = parms.getUploadSpeed();
			String macAddress = parms.getMACAddress();
			String old_serialnumber = parms.getOld_SerialNumber();
			String status = parms.getStatus();

			// Check if parameter is not null or have no value
			ispHelper.isNotNull(macAddress, ISPConstants.MACAddress);

			// Construct Provision Request
			ModifyRequest modReq = new ModifyRequest();
			modReq.setAction(ISPConstants.ACTION_UPDATE);
			modReq.setMACAddress(macAddress);
			if(serialnumber!=null) {
				modReq.setSerialNumber(serialnumber);
			}
			if(old_serialnumber!=null) {
				modReq.setOldSerialNumber(old_serialnumber);
			}
			
			if(status!=null) {
				modReq.setStatus(status);
			}
			
			Service service=new Service();

			if(downloadspeed!=null) {
				service.setDownloadSpeed(downloadspeed);	
			}
			if(uploadspeed!=null) {
				service.setUploadSpeed(uploadspeed);	
			}

			Credential cred = new Credential();
			cred.setUser(connHdlr.getUserId());
			cred.setAuthentication(connHdlr.getPassword());

			if(service!=null) {
				modReq.setService(service);
			}
			modReq.setCredential(cred);

			String modReqStr = ispHelper.getRequestString(modReq);
			logger.logDebug("Change Request - " + modReqStr);

			ModifyResponse modRes =null;
			if (!systemParameters.isLoopback()) {

				String modResStr = connHdlr.sendRequest(modReqStr);

				Unmarshaller unmarshaller = JAXBContext.newInstance(ModifyResponse.class).createUnmarshaller();

				modRes = (ModifyResponse) unmarshaller.unmarshal(new StringReader(modResStr));

			}
			else {
				
				ModifyResponse resp=new ModifyResponse();
				resp.setDesc("SUCCESS");
				resp.setResult(0);

				String modResStr = ispHelper.getModifyResponse(resp);
				logger.logDebug("Modify response - " + modResStr);

				Unmarshaller unmarshaller = JAXBContext.newInstance(ModifyResponse.class).createUnmarshaller();

				modRes = (ModifyResponse) unmarshaller.unmarshal(new StringReader(modResStr));

			}
			int Result = modRes.getResult();

			responseCode = Integer.toString(Result);
			responseDesc = modRes.getDesc();
		}
		catch(Exception ex)
		{
			responseCode = ispHelper.getExceptionResponseCode(ex);
			responseDesc = ex.getMessage()+" in "+jproc.getParam(ISPConstants.CSDL_CMD);
			logger.logError("Exception occurred: "+ex.toString());
		}

		finally
		{
			String exitValue = exitType.setTypeByMatch(responseCode, 
					responseDesc, IExitType.FAIL);

			if ((exitValue != null) && (exitValue.equals(IExitType.FAIL))) {
				output.addActionParameter(PARAMETER_ERROR, responseDesc);
				output.addActionParameter(PARAMETER_VENDOR, VENDOR);
				output.addActionParameter(PARAMETER_TECHNOLOGY, TECHNOLOGY);
				output.addActionParameter(PARAMETER_SOFTWARE_LOAD, SOFTWARE_LOAD);
			}
		}
	}

	/**
	 * The init method is called prior to the execute method.  Additional initialization logic may be added as necessary.
	 *
	 * @param processor a reference to the underlying proxy processor.  Use of this parameter is strongly discouraged.
	 * @param logger a logging instance to be used for all processor logging.
	 */
	public void init(Object processor, ILogger logger) {
		this.logger = logger;
		//If connected to network set Loopback response
		//responseCode = ISPConstants.DEFAULT_SUCCESS_CODE;
		//responseDesc = ISPConstants.SUCCESS;

		if (processor instanceof JProcessor) {
			jproc = (JProcessor) processor;
		}	
	}

}