/**
 * TODO Copyright Notice
 */
package com.oracle.activation.eric.mobile.x2_0.sub_mobile_data.sus;

import com.oracle.activation.eric.mobile.x2_0.ConnectionHandler;
import com.oracle.activation.eric.mobile.x2_0.Helper;
import com.oracle.activation.eric.mobile.x2_0.MobConstants;
import com.oracle.activation.eric.mobile.x2_0.sub_mobile_data.sus.generated.*;

import java.util.HashMap;

import com.mslv.activation.jinterpreter.JProcessor;
import com.mslv.studio.activation.implementation.IConnectionHandler;
import com.mslv.studio.activation.implementation.ILogger;
import com.mslv.studio.activation.implementation.IExitType;


public class SusSub_mobile_dataProcessor implements SusSub_mobile_dataProcessorInterface {

	/*
	 * The logger to use for all log information generated by this processor.
	 */
	private ILogger logger = null;
	private String responseDesc = null;
	private JProcessor jproc=null;
	private String responseCode = null;

	public void execute(SusSub_mobile_dataInput parms, SusSub_mobile_dataOutput output, IConnectionHandler connection,
			IExitType exitType, ISystemParameters systemParameters) throws Exception {

		// TODO  Log intermediate steps of process execution. 
		logger.logDebug("execute() - Completed step A of execution.");
		try {

			logger.logDebug("SusSub_mobile_dataProcessor: execute() - Completed step A of execution.");
			logger.logDebug("JPROC CSDL_CMD "+jproc.getParam(MobConstants.CSDL_CMD));

			ConnectionHandler connHdlr = (ConnectionHandler) connection;

			// Sample code to extract the parameters from the Input bean.

			String mcli = parms.getMCLI();
			String imsi = parms.getIMSI();
			String msisdn = parms.getMSISDN();

			HashMap<String, String> hm = new HashMap<>();

			hm.put(MobConstants.SERVICE, "data");
			hm.put(MobConstants.MSISDN, msisdn);
			hm.put(MobConstants.IMSI, imsi);

			// Construct Provision Request
			logger.logDebug("ISLOOPBACK_SYSTEMPARAMETERS "+systemParameters.isLoopback());
			if (!systemParameters.isLoopback()) {
				responseCode = connHdlr.sendRequest(hm,MobConstants.SUSPEND,true);
			}
			else
			{
				responseCode = connHdlr.sendRequest(hm,MobConstants.SUSPEND, false);
			}
		}

		catch(Exception ex)
		{
			responseCode = Helper.getExceptionResponseCode(ex);
			responseDesc = ex.getMessage()+" in "+jproc.getParam(MobConstants.CSDL_CMD);
			logger.logError("Exception occurred: "+ex.toString());
		}


		finally
		{

			logger.logDebug("responseMessage "+responseDesc);

			String exitValue = exitType.setTypeByMatch(responseCode, 
					responseDesc, IExitType.FAIL);

			if ((exitValue != null) && (exitValue.equals(IExitType.FAIL))) {
				output.addActionParameter(PARAMETER_ERROR, responseDesc);
				output.addActionParameter(PARAMETER_VENDOR, VENDOR);
				output.addActionParameter(PARAMETER_TECHNOLOGY, TECHNOLOGY);
				output.addActionParameter(PARAMETER_SOFTWARE_LOAD, SOFTWARE_LOAD);
			}
		}

	}

	/**
	 * The init method is called prior to the execute method.  Additional initialization logic may be added as necessary.
	 *
	 * @param processor a reference to the underlying proxy processor.  Use of this parameter is strongly discouraged.
	 * @param logger a logging instance to be used for all processor logging.
	 */
	public void init(Object processor, ILogger logger) {
		this.logger = logger;
		if (processor instanceof JProcessor) {
			jproc = (JProcessor) processor;
		}
	}

}